version: 0.0
os: windows
files:
  - source: \
    destination: C:\deploy
hooks:
  ApplicationStart:
    - location: s3_transfer.ps1
      timeout: 300
# 🔴【重要】これと同じインデント（左詰め）で最下部に追加してください
file_exists_behavior: OVERWRITE