version: 0.0
os: windows
files:
  - source: \
    destination: C:\deploy
file_exists_behavior: OVERWRITE
hooks:
  # 💡 まだファイルがないフェーズなので、中身を空（何もしない）にします
  BeforeInstall: []
  
  # 💡 古いスクリプトがなくてもエラーを無視して進めます
  ApplicationStop:
    - location: s3_transfer.ps1
      timeout: 30
    allow_lifecycle_event_errors: true

  # 💡 ここで最新のスクリプトを安全に実行します
  ApplicationStart:
    - location: s3_transfer.ps1
      timeout: 300