version: 0.0
os: windows
files:
  - source: \
    destination: C:\deploy
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: s3_transfer.ps1
      timeout: 30
  BeforeInstall:
    - location: s3_transfer.ps1
      timeout: 30
  ApplicationStart:
    - location: s3_transfer.ps1
      timeout: 300

# 🔴 全てのフックで「エラーが起きても無視して進む」設定を、インデントなしのルート（一番左）に書きます
allow_lifecycle_event_errors: true